name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: password
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-progress --no-scripts --no-suggest --optimize-autoloader

    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate application key
      run: php artisan key:generate

    - name: Create test database
      run: |
        psql -U laravel -d laravel_test -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
        php artisan migrate --env=testing --force --no-interaction
        php artisan db:seed --env=testing --force --no-interaction

    - name: Run Pest tests
      run: ./vendor/bin/pest

    - name: Post Run Cleanup
      run: php artisan migrate:rollback --env=testing --force
